/**
 * Frontend enum module.
 *
 * The TYPES are re-exported from `generated.d.ts`, which is auto-generated by
 * `php artisan typescript:transform` from `app/Enums/*.php` (the source of
 * truth). Regenerate after changing any PHP enum. This file only adds the
 * UI-facing label maps on top — the `Record<…>` typing makes a new enum case
 * fail to compile here until it's given a label, so drift is caught early.
 */

export type UserRole = App.Enums.UserRole;
export type InvitationStatus = App.Enums.InvitationStatus;
export type AccountStatus = App.Enums.AccountStatus;
export type DocumentType = App.Enums.DocumentType;

export const userRoleLabel: Record<UserRole, string> = {
    admin: 'Admin',
    mentor: 'Mentor',
    entrepreneur: 'Entrepreneur',
    employee: 'Employee',
};

/** Roles an admin may issue an invitation for (mirrors UserRole::invitable()). */
export const invitableRoles: UserRole[] = ['entrepreneur', 'mentor', 'admin'];

export const invitationStatusLabel: Record<InvitationStatus, string> = {
    pending: 'Pending',
    accepted: 'Accepted',
    revoked: 'Revoked',
    expired: 'Expired',
};

export const accountStatusLabel: Record<AccountStatus, string> = {
    approved: 'Approved',
    deactivated: 'Deactivated',
};
